defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Your Name Website
subtitle: Digital Fab & Prototyping Fundamentals
theme: panthera-jekyll
# remote-theme: christianezeani/panthera-jekyll

# Side Menu Links
menu:
  - text: Home
    link: /
    icon: ""

  - text: About
    link: /about.md
    icon: ""

  - text: Fablab Safety
    link: /docs/safety.md
    icon: ""

  - text: Project Management
    link: /docs/proj-mgmt.md
    icon: ""

  - text: Web Development
    link: /docs/web.md
    icon: ""

  - text: Computer Aided Design
    link: /docs/cad.md
    icon: ""

  - text: Embedded Programming
    link: /docs/embedded
    icon: ""

  - text: 3D Printing
    link: /docs/3dprint.md
    icon: ""

  - text: Laser Cutting
    link: /docs/laser.md
    icon: ""

  - text: Final Project
    link: /docs/project.md
    icon: ""

  - text: Contact
    link: /contact.md
    icon: ""


# Socialmedia Icons
social_icons:
  - name: linkedin
    link: ""
    icon: fab fa-linkedin

  - name: github
    link: ""
    icon: fab fa-github-square

  - name: facebook
    link: ""
    icon: fab fa-facebook-square

  - name: twitter
    link: ""
    icon: fab fa-twitter
